apiVersion: v1
kind: Service
metadata:
  name: pocapi-service
spec:
  ports:
  - port: 82
    targetPort: 82
    protocol: TCP
    name: http
  selector:
    app: pocapi
  type: LoadBalancer


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pocapi
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pocapi
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key2
      containers:
      - name: pocapi
        image: PocApi
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        ports:
          - containerPort: 82
        resources:
          limits:
            cpu: "1"
            memory: 3Gi
          requests:
            cpu: 400m
            memory: 2Gi