version: '3.1'

services:

  db:
    image: postgres:alpine
    container_name: postgres_server
    restart: always
    environment:
      POSTGRES_USER: pocstone
      POSTGRES_PASSWORD: pocstone
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
