// <auto-generated />
using System;
using Infra.AcessoBaseDados.AcessoPostgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infra.Migrations
{
    [DbContext(typeof(ContextoPostgres))]
    partial class ContextoPostgresModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Dominio.Entidades.Pagamentos", b =>
                {
                    b.Property<string>("codPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("dataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("rastreio")
                        .HasColumnType("text");

                    b.Property<string>("statusPagamento")
                        .HasColumnType("text");

                    b.Property<string>("tipoDePagamento")
                        .HasColumnType("text");

                    b.Property<double>("valor")
                        .HasColumnType("double precision");

                    b.HasKey("codPagamento");

                    b.ToTable("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
